# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' EBMA Calculation Using C++
#'
#' @param x Numeric matrix of  predictions from each model.
#' @param y Numeric vector of actual (observed) outcomes.
#' @param W_Hats Numeric vector of the weight assigned to each model.
#' @param sd Standard deviation.
#' @param tol Tolerance threshold after which iteration ends.
#'
#' @export
CPP_EBMA <- function(x, y, W_Hats, sd, tol) {
    .Call(`_rcppEBMA_CPP_EBMA`, x, y, W_Hats, sd, tol)
}

#' W-Hat Re-weighting Computation.
#'
#'
#' @param Z_H Numeric matrix of z-hat values, derived in Z_H function
#'
#' @export
NULL

W_H <- function(Z_H) {
    .Call(`_rcppEBMA_W_H`, Z_H)
}

#' Z-Hat/Computation: Predicting Z Values.
#'
#' @param x Numeric matrix of model predictions.
#' @param y Vector of actual (observed) outcomes for each observation.
#' @param W_H Vector of weights with each element corresponding to a model.
#' @param sd Standard deviation.
#'
#' @export
NULL

Z_H <- function(x, y, W_H, sd) {
    .Call(`_rcppEBMA_Z_H`, x, y, W_H, sd)
}

rcpp_hello_world <- function() {
    .Call(`_rcppEBMA_rcpp_hello_world`)
}

